name: Build Eclipse eMoflon
on:
  push:
    # Run pipeline for commits on branch 'main' and on 'testing/<stuff>'
    branches:
      - main
      - 'testing/**'
      - 'archive/**'
    # Run pipeline for release tags
    tags:
      - 'v*.*.*'

jobs:
  # Build Eclipse eMoflon Linux user
  build-linux-user:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m user -o linux
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user
          path: eclipse-emoflon-linux-user.zip

  # Build Eclipse eMoflon Linux dev
  build-linux-dev:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m dev -o linux
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev
          path: eclipse-emoflon-linux-dev.zip

  # Build Eclipse eMoflon Linux user CI
  build-linux-user-ci:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux user CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m user -o linux --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-user.zip eclipse-emoflon-linux-user-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-user-ci
          path: eclipse-emoflon-linux-user-ci.zip

  # Build Eclipse eMoflon Linux dev CI
  build-linux-dev-ci:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Linux dev CI)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: chmod +x build.sh && ./build.sh -m dev -o linux --skip-theme
      - name: Rename ZIP archive
        run: mv eclipse-emoflon-linux-dev.zip eclipse-emoflon-linux-dev-ci.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-linux-dev-ci
          path: eclipse-emoflon-linux-dev-ci.zip

  # Build Eclipse eMoflon Windows user
  build-windows-user:
    runs-on: [self-hosted, windows, x64]
    env:
      WINDOWS_JDK_BIN_PATH: ${{ secrets.WINDOWS_JDK_BIN_PATH }}
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows user)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: |
          echo "$env:WINDOWS_JDK_BIN_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          bash ./build.sh -m user -o windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-user
          path: eclipse-emoflon-windows-user.zip

  # Build Eclipse eMoflon Windows dev
  build-windows-dev:
    runs-on: [self-hosted, windows, x64]
    env:
      WINDOWS_JDK_BIN_PATH: ${{ secrets.WINDOWS_JDK_BIN_PATH }}
    steps:
      - name: Start message
        run: echo "Started CI build (Eclipse eMoflon Windows dev)."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build script
        run: |
          echo "$env:WINDOWS_JDK_BIN_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          bash ./build.sh -m dev -o windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eclipse-emoflon-windows-dev
          path: eclipse-emoflon-windows-dev.zip

  # Create a release if running on tag
  create-release:
    needs: [build-linux-user, build-linux-dev, build-linux-user-ci, build-linux-dev-ci, build-windows-user, build-windows-dev]
    runs-on: [self-hosted, linux, x64]
    # Only run on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Collect artifacts
        uses: actions/download-artifact@master
      - name: Release eclipse-emoflon-linux
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-linux-user/eclipse-emoflon-linux-user.zip
            eclipse-emoflon-linux-dev/eclipse-emoflon-linux-dev.zip
      - name: Release eclipse-emoflon-linux-ci
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-linux-user-ci/eclipse-emoflon-linux-user-ci.zip
            eclipse-emoflon-linux-dev-ci/eclipse-emoflon-linux-dev-ci.zip
      - name: Release eclipse-emoflon-windows
        uses: softprops/action-gh-release@v1
        with:
          files: |
            eclipse-emoflon-windows-user/eclipse-emoflon-windows-user.zip
            eclipse-emoflon-windows-dev/eclipse-emoflon-windows-dev.zip
